import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const New: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://raw.githubusercontent.com/Semantic-Org/UI-Icon/master/icon.min.css" />
        </Head>

        <main className={styles.main}>
          <a
            id="skip-to-main"
            className="ui button primary ml-5 mt-5 skip-link"
            href="#main"
          >
            Skip to main
          </a>

          <div>
            <header className="theme header">
              <div className="outer-navbar">
                <div className="ui container invenio-header-container">
                  <nav
                    id="invenio-nav"
                    className="ui inverted menu borderless stackable p-0"
                  >
                    <div className="item logo p-0">
                      <a className="logo-link" href="/">
                        <img
                          className="ui image rdm-logo"
                          src="/coco-logo.png"
                          alt="InvenioRDM"
                        />
                      </a>
                    </div>

                    <div id="rdm-burger-toggle">
                      <button
                        id="rdm-burger-menu-icon"
                        className="ui button transparent"
                        aria-label="Menu"
                        aria-haspopup="menu"
                        aria-expanded="false"
                        aria-controls="invenio-menu"
                      >
                        <span className="navicon"></span>
                      </button>
                    </div>

                    <div
                      role="menu"
                      id="invenio-menu"
                      aria-labelledby="rdm-burger-menu-icon"
                      className="ui fluid menu borderless mobile-hidden"
                    >
                      <button
                        id="rdm-close-burger-menu-icon"
                        className="ui button transparent"
                        aria-label="Close menu"
                      >
                        <span className="navicon"></span>
                      </button>
                      <div className=" item">
                        <a role="menuitem" href="/communities">
                          Communities
                        </a>
                      </div>

                      <div className="item">
                        <a role="menuitem" href="/me/uploads">
                          My dashboard
                        </a>
                      </div>

                      <div className="right menu item">
                        <form>
                          <a href="/login/?next=%2F" className="ui button">
                            <i className="sign-in icon"></i>
                            Log in
                          </a>

                          <a href="/signup/" className="ui button signup">
                            <i className="edit outline icon"></i>
                            Sign up
                          </a>
                        </form>
                      </div>
                    </div>
                  </nav>
                  <div
                    id="frontpage-search-bar"
                    className="ui container fluid frontpage-header"
                  >
                    <div className="ui container grid rel-mt-2">
                      <div className="row">
                        <div className="sixteen wide column center aligned">
                          <h1 className="ui center aligned header inverted">
                            Welcome to InvenioRDM's Sandbox!
                          </h1>
                        </div>
                      </div>
                      <div className="row">
                        <div className="sixteen wide mobile four wide computer column"></div>
                        <div className="sixteen wide mobile eight wide computer column center aligned">
                          <form
                            action="/search"
                            className="ui form"
                            role="search"
                          >
                            <div className="ui fluid big action input">
                              <input
                                type="text"
                                name="q"
                                className="form-control"
                                placeholder="Search"
                              />
                              <button
                                type="submit"
                                className="ui icon search button"
                                aria-label="Search"
                              >
                                <i className="search icon"></i>
                              </button>
                            </div>
                          </form>
                        </div>
                      </div>
                      <div className="ui divider hidden"></div>
                    </div>
                  </div>
                </div>
              </div>
            </header>
          </div>

          <main id="main">
            <div className="invenio-page-body">
              <section className="invenio-rdm-project-section section-content white-bg">
                <h2 className="section-title">
                  Sandbox deployment of InvenioRDM
                </h2>
                <div className="ui container two column grid center aligned vertically padded relaxed stackable">
                  <div className="row one column">
                    <div className="column">
                      <p>Here you can test all the features it has to offer!</p>
                    </div>
                  </div>
                  <div className="rdm-goal six wide column">
                    <i className="key huge icon"></i>
                    <h3>Repository Platform</h3>
                    <p>
                      InvenioRDM is a turn-key research data management (RDM)
                      repository platform based on{' '}
                      <a href="https://inveniosoftware.org/products/framework/">
                        Invenio Framework
                      </a>{' '}
                      and <a href="https://www.zenodo.org">Zenodo</a>.
                    </p>
                  </div>

                  <div className="rdm-goal six wide column">
                    <i className="users huge icon"></i>
                    <h3>Open Source</h3>
                    <p>
                      InvenioRDM is Open Source and has a big community behind
                      it. You can
                      <a href="https://inveniordm.docs.cern.ch">
                        deploy your own instance
                      </a>{' '}
                      in just a few steps.
                    </p>
                  </div>
                  <div className="row one column">
                    <div className="column">
                      <p>
                        More information on the{' '}
                        <a href="https://inveniosoftware.org/products/rdm">
                          InvenioRDM product page
                        </a>
                      </p>
                    </div>
                  </div>
                </div>
              </section>
              <section className="brought-to-you-section section-content light-bg">
                <h2 className="section-title frontpage-title">
                  Brought to you by
                </h2>
                <div className="ui container">
                  <div className="ui relaxed vertically padded centered grid stackable">
                    <div className="rdm-collaborators four wide column">
                      <a href="https://www.nyu.edu/">
                        <img
                          className="collaborators-logo"
                          src="https://inveniordm.web.cern.ch/static/images/logo-nyu.png"
                          title="New York University"
                        ></img>
                      </a>
                    </div>
                    <div className="rdm-collaborators four wide column">
                      <a href="https://www.northwestern.edu/">
                        <img
                          className="collaborators-logo"
                          src="https://inveniordm.web.cern.ch/static/images/logo-northwestern-university.png"
                          title="Northwestern University"
                        ></img>
                      </a>
                    </div>
                    <div className="rdm-collaborators four wide column">
                      <a href="https://www.openaire.eu/">
                        <img
                          className="collaborators-logo"
                          src="https://inveniordm.web.cern.ch/static/images/logo-openaire.png"
                          title="OpenAIRE"
                        ></img>
                      </a>
                    </div>
                    <div className="rdm-collaborators four wide column">
                      <a href="https://tind.io/">
                        <img
                          className="collaborators-logo"
                          src="https://inveniordm.web.cern.ch/static/images/logo-tind.png"
                          title="TIND"
                        ></img>
                      </a>
                    </div>
                    <div className="rdm-collaborators four wide column">
                      <a href="https://ulakbim.tubitak.gov.tr">
                        <img
                          className="collaborators-logo"
                          src="https://inveniordm.web.cern.ch/static/images/logo-tubitak.svg"
                          title="Tubitak"
                        ></img>
                      </a>
                    </div>
                    <div className="rdm-collaborators four wide column">
                      <a href="https://www.tugraz.at/en/home/">
                        <img
                          className="collaborators-logo"
                          src="https://inveniordm.web.cern.ch/static/images/logo-tu-graz.svg"
                          title="TU Graz"
                        ></img>
                      </a>
                    </div>
                    <div className="rdm-collaborators four wide column">
                      <a href="https://www.tuwien.at/">
                        <img
                          className="collaborators-logo"
                          src="https://inveniordm.web.cern.ch/static/images/logo-tu-wien.svg"
                          title="TU Wien"
                        ></img>
                      </a>
                    </div>
                    <div className="rdm-collaborators four wide column">
                      <a href="https://www.uni-hamburg.de/">
                        <img
                          className="collaborators-logo"
                          src="https://inveniordm.web.cern.ch/static/images/logo-uni-hamburg.png"
                          title="Universität Hamburg"
                        ></img>
                      </a>
                    </div>
                    <div className="rdm-collaborators four wide column">
                      <a href="https://www.uni-muenster.de/en/">
                        <img
                          className="collaborators-logo"
                          src="https://inveniordm.web.cern.ch/static/images/logo-uni-munster.png"
                          title="University of Münster"
                        ></img>
                      </a>
                    </div>
                    <div className="rdm-collaborators four wide column">
                      <a href="https://uni-tuebingen.de/en/">
                        <img
                          className="collaborators-logo"
                          src="https://inveniordm.web.cern.ch/static/images/logo-uni-tubingen.png"
                          title="University of Tübingen"
                        ></img>
                      </a>
                    </div>
                    <div className="rdm-collaborators four wide column">
                      <a href="https://www.wacren.net">
                        <img
                          className="collaborators-logo"
                          src="https://inveniordm.web.cern.ch/static/images/logo-wacren.png"
                          title="West and Central African Research and Education Network"
                        ></img>
                      </a>
                    </div>
                  </div>
                </div>
              </section>
            </div>
          </main>

          <footer id="rdm-footer-element">
            <div className="footer-top">
              <div className="ui container">
                <div className="ui grid">
                  <div className="rdm-footer five wide tablet two wide computer column">
                    <h2 className="ui small header">About InvenioRDM</h2>

                    <p>
                      <a href="http://inveniosoftware.org/products/rdm">
                        Product page
                      </a>
                    </p>

                    <p>
                      <a href="https://inveniosoftware.org/products/rdm/#features">
                        Features
                      </a>
                    </p>

                    <p>
                      <a href="https://inveniosoftware.org/products/rdm/roadmap/">
                        Roadmap
                      </a>
                    </p>

                    <p>
                      <a href="http://inveniordm.web.cern.ch">Demo site</a>
                    </p>
                  </div>
                  <div className="rdm-footer five wide tablet two wide computer column">
                    <h2 className="ui small header">Get involved</h2>

                    <p>
                      <a href="https://github.com/inveniosoftware/invenio-app-rdm">
                        GitHub
                      </a>
                    </p>

                    <p>
                      <a href="https://github.com/inveniosoftware/product-rdm">
                        Project Milestones
                      </a>
                    </p>

                    <p>
                      <a href="http://inveniordm.docs.cern.ch">Documentation</a>
                    </p>
                  </div>
                  <div className="rdm-footer five wide tablet two wide computer column">
                    <h2 className="ui small header">Community</h2>

                    <p>
                      <a href="https://discord.gg/8qatqBC">Chatroom</a>
                    </p>

                    <p>
                      <a href="https://invenio-talk.web.cern.ch/c/projects/invenio-rdm">
                        Forum
                      </a>
                    </p>

                    <p>
                      <a href="https://inveniosoftware.org/events/">
                        Events &amp; training
                      </a>
                    </p>
                  </div>
                  <div className="six wide column right aligned"></div>
                </div>
              </div>
            </div>
            <div className="footer-bottom sub-footer">
              <div className="ui container">
                <div className="ui grid">
                  <div className="eight wide column left middle aligned">
                    Powered by{' '}
                    <a href="http://inveniosoftware.org/products/rdm">
                      InvenioRDM
                    </a>
                  </div>
                  <div className="eight wide column right aligned"></div>
                </div>
              </div>
            </div>
          </footer>
        </main>
      </div>
    </>
  )
}

export default New
