import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const New: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://raw.githubusercontent.com/Semantic-Org/UI-Icon/master/icon.min.css" />
        </Head>

        <main className={styles.main}>
          <a
            id="skip-to-main"
            className="ui button primary ml-5 mt-5 skip-link"
            href="#main"
          >
            Skip to main
          </a>

          <div>
            <header className="theme header">
              <div className="outer-navbar">
                <div className="ui container invenio-header-container">
                  <nav
                    id="invenio-nav"
                    className="ui inverted menu borderless stackable p-0"
                  >
                    <div className="item logo p-0">
                      <a className="logo-link" href="/">
                        <img
                          className="ui image rdm-logo"
                          src="/coco-logo.png"
                          alt="InvenioRDM"
                        />
                      </a>
                    </div>

                    <div id="rdm-burger-toggle">
                      <button
                        id="rdm-burger-menu-icon"
                        className="ui button transparent"
                        aria-label="Menu"
                        aria-haspopup="menu"
                        aria-expanded="false"
                        aria-controls="invenio-menu"
                      >
                        <span className="navicon"></span>
                      </button>
                    </div>

                    <div
                      role="menu"
                      id="invenio-menu"
                      aria-labelledby="rdm-burger-menu-icon"
                      className="ui fluid menu borderless mobile-hidden"
                    >
                      <button
                        id="rdm-close-burger-menu-icon"
                        className="ui button transparent"
                        aria-label="Close menu"
                      >
                        <span className="navicon"></span>
                      </button>

                      <div className="item p-0 search-bar rel-mr-1">
                        <div
                          id="header-search-bar"
                          data-options='[{"key": "records", "text": "All InvenioRDM", "value": "/search"}]'
                        >
                          <div className="ui fluid search">
                            <div className="ui icon input">
                              <input
                                placeholder="Search records..."
                                type="text"
                                className="prompt"
                                value=""
                              />
                              <i aria-hidden="true" className="search icon"></i>
                            </div>
                            <div className="results transition">
                              <div
                                text="All InvenioRDM"
                                value="/search"
                                className="active result"
                              >
                                <div className="flex">
                                  <div className="truncated pt-5"></div>
                                  <div className="ui label right-floated">
                                    All InvenioRDM
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div className=" item">
                        <a role="menuitem" href="/communities">
                          Communities
                        </a>
                      </div>

                      <div className="item">
                        <a role="menuitem" href="/me/uploads">
                          My dashboard
                        </a>
                      </div>

                      <div className="right menu item">
                        <form>
                          <a
                            href="/login/?next=%2Fsearch"
                            className="ui button"
                          >
                            <i className="sign-in icon"></i>
                            Log in
                          </a>

                          <a href="/signup/" className="ui button signup">
                            <i className="edit outline icon"></i>
                            Sign up
                          </a>
                        </form>
                      </div>
                    </div>
                  </nav>
                </div>
              </div>
            </header>
          </div>

          <main id="main">
            <div className="ui container">
              <div className="ui relaxed grid">
                <div className="right aligned two column row result-options rel-mt-2">
                  <div className="mobile only tablet only center aligned middle aligned two wide mobile one wide tablet column">
                    <button
                      aria-label="Filter results"
                      className="ui basic icon button"
                    >
                      <i aria-hidden="true" className="sliders icon"></i>
                    </button>
                  </div>
                  <div className="right floated twelve wide computer thirteen wide large screen fourteen wide mobile fifteen wide tablet thirteen wide widescreen column">
                    <div className="ui grid">
                      <div className="middle aligned row">
                        <div className="left aligned eight wide column">
                          <div className="ui label">147</div> result(s) found
                          <br />
                        </div>
                        <div className="right aligned eight wide column">
                          <div
                            aria-label="Sort"
                            role="listbox"
                            aria-expanded="false"
                            className="ui selection dropdown"
                          >
                            <div
                              aria-atomic="true"
                              aria-live="polite"
                              role="alert"
                              className="divider text"
                            >
                              Newest
                            </div>
                            <i aria-hidden="true" className="dropdown icon"></i>
                            <div className="menu transition">
                              <div
                                role="option"
                                aria-checked="false"
                                aria-selected="false"
                                className="item"
                              >
                                <span className="text">Best match</span>
                              </div>
                              <div
                                role="option"
                                aria-checked="true"
                                aria-selected="true"
                                className="active selected item"
                              >
                                <span className="text">Newest</span>
                              </div>
                              <div
                                role="option"
                                aria-checked="false"
                                aria-selected="false"
                                className="item"
                              >
                                <span className="text">Oldest</span>
                              </div>
                              <div
                                role="option"
                                aria-checked="false"
                                aria-selected="false"
                                className="item"
                              >
                                <span className="text">Version</span>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="two column row">
                  <div className="computer only four wide computer three wide large screen three wide widescreen four wide column">
                    <aside aria-label="filters" id="search-filters">
                      <div className="ui card borderless facet">
                        <div className="content">
                          <h2 className="header">Versions</h2>
                        </div>
                        <div className="content">
                          <div className="ui toggle checkbox">
                            <input
                              className="hidden"
                              id="versions-toggle"
                              name="versions-toggle"
                              type="checkbox"
                              value=""
                            />
                            <label for="versions-toggle">
                              View all versions
                            </label>
                          </div>
                        </div>
                      </div>
                      <div className="rdm-facet-container">
                        <div className="ui card borderless facet">
                          <div className="content">
                            <h2 className="header">Access status</h2>
                            <div role="list" className="ui list">
                              <div role="listitem" className="item">
                                <div className="content facet-wrapper">
                                  <div className="ui checkbox">
                                    <input
                                      aria-describedby="metadata-only-count"
                                      className="hidden"
                                      id="metadata-only-facet-checkbox"
                                      type="checkbox"
                                      value="metadata-only"
                                    />
                                    <label for="metadata-only-facet-checkbox">
                                      Metadata-only
                                    </label>
                                  </div>
                                  <div
                                    id="metadata-only-count"
                                    className="ui circular label facet-count"
                                  >
                                    117
                                  </div>
                                </div>
                              </div>
                              <div role="listitem" className="item">
                                <div className="content facet-wrapper">
                                  <div className="ui checkbox">
                                    <input
                                      aria-describedby="open-count"
                                      className="hidden"
                                      id="open-facet-checkbox"
                                      type="checkbox"
                                      value="open"
                                    />
                                    <label>Open</label>
                                  </div>
                                  <div
                                    id="open-count"
                                    className="ui circular label facet-count"
                                  >
                                    26
                                  </div>
                                </div>
                              </div>
                              <div role="listitem" className="item">
                                <div className="content facet-wrapper">
                                  <div className="ui checkbox">
                                    <input
                                      aria-describedby="restricted-count"
                                      className="hidden"
                                      id="restricted-facet-checkbox"
                                      type="checkbox"
                                      value="restricted"
                                    />
                                    <label>Restricted</label>
                                  </div>
                                  <div
                                    id="restricted-count"
                                    className="ui circular label facet-count"
                                  >
                                    4
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="ui card borderless facet mt-0">
                        <div className="content">
                          <h2 className="header">Help</h2>
                          <div role="list" className="ui list">
                            <div role="listitem" className="item">
                              <a href="/help/search">Search guide</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </aside>
                  </div>{' '}
                  <div className="twelve wide computer thirteen wide large screen sixteen wide mobile sixteen wide tablet thirteen wide widescreen column">
                    <div className="ui relaxed grid">
                      <div className="row">
                        <div className="column">
                          <div className="ui divided link relaxed items">
                            <div className="item">
                              <div className="content">
                                <div className="extra labels-actions">
                                  <div className="ui tiny label primary">
                                    December 6, 2021 (Final)
                                  </div>
                                  <div className="ui tiny label neutral">
                                    Book
                                  </div>
                                  <div className="ui tiny label access-status metadata-only">
                                    <i className="icon tag"></i>Metadata-only
                                  </div>
                                </div>
                                <h2 className="header">
                                  <a href="/records/wzs0j-p8k21">
                                    Somme archivistique issue d'Afrique et
                                    d'ailleurs : Contribution à l'éveil de tous
                                    sur l'importance des mémoires documentaires
                                  </a>
                                </h2>
                                <div className="item creatibutors">
                                  <span className="creatibutor-wrap separated">
                                    <a
                                      className="creatibutor-link"
                                      href='/search?q=metadata.creators.person_or_org.name:"Diouf, Antonin Benoît"'
                                      title="Diouf, Antonin Benoît: Search"
                                    >
                                      <span className="creatibutor-name">
                                        Diouf, Antonin Benoît
                                      </span>
                                    </a>
                                    <a
                                      className="no-text-decoration mr-0"
                                      href="https://orcid.org/0000-0002-1000-6882"
                                      aria-label="Diouf, Antonin Benoît: ORCID profile"
                                      title="Diouf, Antonin Benoît: ORCID profile"
                                    >
                                      <img
                                        className="inline-id-icon ml-5"
                                        src="/static/images/orcid.svg"
                                        alt=""
                                      />
                                    </a>
                                  </span>
                                </div>
                                <div className="description">
                                  Un exposé panoramique critique de la réalité
                                  archivistique en quatre temps. Tout d'abord,
                                  un récit typologique des supports de contenus,
                                  dont l'évolution, a traversé les âges. Ils
                                  constituent depuis lors l'objet déterminant de
                                  la politique archivistique universelle. Une
                                  politique décrite à la suite, présentant
                                  certaines particularités contextuel...
                                </div>
                                <div className="extra">
                                  <div>
                                    <small>
                                      Uploaded on <span>August 28, 2022</span>
                                    </small>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div floated="right" className="middle aligned row">
                        <div className="four wide column computer tablet only"></div>
                        <div className="center aligned eight wide column computer tablet only">
                          <div
                            aria-label="Pagination Navigation"
                            role="navigation"
                            className="ui mini pagination menu"
                          >
                            <a
                              aria-current="false"
                              aria-disabled="false"
                              tabindex="0"
                              value="1"
                              aria-label="Previous item"
                              type="prevItem"
                              className="item"
                            >
                              ⟨
                            </a>
                            <a
                              aria-current="true"
                              aria-disabled="false"
                              tabindex="0"
                              value="1"
                              type="pageItem"
                              className="active item"
                            >
                              1
                            </a>
                            <a
                              aria-current="false"
                              aria-disabled="false"
                              tabindex="0"
                              value="2"
                              type="pageItem"
                              className="item"
                            >
                              2
                            </a>
                            <a
                              aria-current="false"
                              aria-disabled="false"
                              tabindex="0"
                              value="3"
                              type="pageItem"
                              className="item"
                            >
                              3
                            </a>
                            <a
                              aria-current="false"
                              aria-disabled="false"
                              tabindex="0"
                              value="4"
                              type="pageItem"
                              className="item"
                            >
                              4
                            </a>
                            <a
                              aria-current="false"
                              aria-disabled="false"
                              tabindex="0"
                              value="5"
                              type="pageItem"
                              className="item"
                            >
                              5
                            </a>
                            <a
                              aria-current="false"
                              aria-disabled="true"
                              tabindex="-1"
                              value="6"
                              type="ellipsisItem"
                              className="item"
                            >
                              ...
                            </a>
                            <a
                              aria-current="false"
                              aria-disabled="false"
                              tabindex="0"
                              value="15"
                              type="pageItem"
                              className="item"
                            >
                              15
                            </a>
                            <a
                              aria-current="false"
                              aria-disabled="false"
                              tabindex="0"
                              value="2"
                              aria-label="Next item"
                              type="nextItem"
                              className="item"
                            >
                              ⟩
                            </a>
                          </div>
                        </div>
                        <div className="center aligned sixteen wide column mobile only">
                          <div
                            aria-label="Pagination Navigation"
                            role="navigation"
                            className="ui large pagination menu"
                          >
                            <a
                              aria-current="false"
                              aria-disabled="false"
                              tabindex="0"
                              value="1"
                              aria-label="Previous item"
                              type="prevItem"
                              className="item"
                            >
                              ⟨
                            </a>
                            <a
                              aria-current="true"
                              aria-disabled="false"
                              tabindex="0"
                              value="1"
                              type="pageItem"
                              className="active item"
                            >
                              1
                            </a>
                            <a
                              aria-current="false"
                              aria-disabled="false"
                              tabindex="0"
                              value="2"
                              type="pageItem"
                              className="item"
                            >
                              2
                            </a>
                            <a
                              aria-current="false"
                              aria-disabled="false"
                              tabindex="0"
                              value="3"
                              type="pageItem"
                              className="item"
                            >
                              3
                            </a>
                            <a
                              aria-current="false"
                              aria-disabled="false"
                              tabindex="0"
                              value="4"
                              type="pageItem"
                              className="item"
                            >
                              4
                            </a>
                            <a
                              aria-current="false"
                              aria-disabled="true"
                              tabindex="-1"
                              value="5"
                              type="ellipsisItem"
                              className="item"
                            >
                              ...
                            </a>
                            <a
                              aria-current="false"
                              aria-disabled="false"
                              tabindex="0"
                              value="2"
                              aria-label="Next item"
                              type="nextItem"
                              className="item"
                            >
                              ⟩
                            </a>
                          </div>
                        </div>
                        <div className="right aligned four wide column computer tablet only ">
                          {' '}
                          <div
                            aria-label="Results per page"
                            role="listbox"
                            aria-expanded="false"
                            className="ui compact inline dropdown"
                            tabindex="0"
                          >
                            <div
                              aria-atomic="true"
                              aria-live="polite"
                              role="alert"
                              className="divider text"
                            >
                              10
                            </div>
                            <i aria-hidden="true" className="dropdown icon"></i>
                            <div className="menu transition">
                              <div
                                role="option"
                                aria-checked="true"
                                aria-selected="true"
                                className="active selected item"
                              >
                                <span className="text">10</span>
                              </div>
                              <div
                                role="option"
                                aria-checked="false"
                                aria-selected="false"
                                className="item"
                              >
                                <span className="text">20</span>
                              </div>
                              <div
                                role="option"
                                aria-checked="false"
                                aria-selected="false"
                                className="item"
                              >
                                <span className="text">50</span>
                              </div>
                            </div>
                          </div>{' '}
                          results per page
                        </div>
                        <div className="center aligned sixteen wide column mobile only mt-10">
                          {' '}
                          <div
                            aria-label="Results per page"
                            role="listbox"
                            aria-expanded="false"
                            className="ui compact inline dropdown"
                            tabindex="0"
                          >
                            <div
                              aria-atomic="true"
                              aria-live="polite"
                              role="alert"
                              className="divider text"
                            >
                              10
                            </div>
                            <i aria-hidden="true" className="dropdown icon"></i>
                            <div className="menu transition">
                              <div
                                role="option"
                                aria-checked="true"
                                aria-selected="true"
                                className="active selected item"
                              >
                                <span className="text">10</span>
                              </div>
                              <div
                                role="option"
                                aria-checked="false"
                                aria-selected="false"
                                className="item"
                              >
                                <span className="text">20</span>
                              </div>
                              <div
                                role="option"
                                aria-checked="false"
                                aria-selected="false"
                                className="item"
                              >
                                <span className="text">50</span>
                              </div>
                            </div>
                          </div>{' '}
                          results per page
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </main>

          <footer id="rdm-footer-element">
            <div className="footer-top">
              <div className="ui container">
                <div className="ui grid">
                  <div className="rdm-footer five wide tablet two wide computer column">
                    <h2 className="ui small header">About InvenioRDM</h2>

                    <p>
                      <a href="http://inveniosoftware.org/products/rdm">
                        Product page
                      </a>
                    </p>

                    <p>
                      <a href="https://inveniosoftware.org/products/rdm/#features">
                        Features
                      </a>
                    </p>

                    <p>
                      <a href="https://inveniosoftware.org/products/rdm/roadmap/">
                        Roadmap
                      </a>
                    </p>

                    <p>
                      <a href="http://inveniordm.web.cern.ch">Demo site</a>
                    </p>
                  </div>
                  <div className="rdm-footer five wide tablet two wide computer column">
                    <h2 className="ui small header">Get involved</h2>

                    <p>
                      <a href="https://github.com/inveniosoftware/invenio-app-rdm">
                        GitHub
                      </a>
                    </p>

                    <p>
                      <a href="https://github.com/inveniosoftware/product-rdm">
                        Project Milestones
                      </a>
                    </p>

                    <p>
                      <a href="http://inveniordm.docs.cern.ch">Documentation</a>
                    </p>
                  </div>
                  <div className="rdm-footer five wide tablet two wide computer column">
                    <h2 className="ui small header">Community</h2>

                    <p>
                      <a href="https://discord.gg/8qatqBC">Chatroom</a>
                    </p>

                    <p>
                      <a href="https://invenio-talk.web.cern.ch/c/projects/invenio-rdm">
                        Forum
                      </a>
                    </p>

                    <p>
                      <a href="https://inveniosoftware.org/events/">
                        Events &amp; training
                      </a>
                    </p>
                  </div>
                  <div className="six wide column right aligned"></div>
                </div>
              </div>
            </div>
            <div className="footer-bottom sub-footer">
              <div className="ui container">
                <div className="ui grid">
                  <div className="eight wide column left middle aligned">
                    Powered by{' '}
                    <a href="http://inveniosoftware.org/products/rdm">
                      InvenioRDM
                    </a>
                  </div>
                  <div className="eight wide column right aligned"></div>
                </div>
              </div>
            </div>
          </footer>
        </main>
      </div>
    </>
  )
}

export default New
